#!/usr/bin/env python3
"""Generate test/golden/dune.inc.

Every `*.cljc` file in this directory is a golden compiler case: it is compiled
against the prebuilt stdlib state and the rendered diagnostics (plus `exit: N`)
are diffed against `<name>.expected`. A `<name>.run` marker file next to the
`.cljc` additionally runs the program and appends its output.

Edit `dune.inc` by running `python3 test/golden/gen_dune_inc.py >
test/golden/dune.inc` — or just `dune promote` when the stale check fails.
"""
import os
import sys

# The case directory is passed explicitly because inside a dune action the
# script runs from the build dir, which does not mirror the source tree.
GOLDEN = (
    sys.argv[1]
    if len(sys.argv) > 1
    else os.path.dirname(os.path.abspath(__file__))
)

STDLIB_STATE = "../../stdlib/lg_stdlib_native.state"
STDLIB_ML = "../../stdlib/lg_stdlib_native.ml"
CLI = "../../bin/lg_cli.exe"


def compile_rule(name):
    return """\
(rule
 (alias runtest)
 (target %s.actual)
 (deps
  run_case.sh
  %s.cljc
  %s.expected
  %s
  %s)
 (action
  (progn
   (with-stdout-to
    %%{target}
    (run
     sh
     %%{dep:run_case.sh}
     compile
     %%{exe:%s}
     %%{dep:%s}
     %%{dep:%s.cljc}))
   (diff %%{dep:%s.expected} %%{target}))))
""" % (
        name,
        name,
        name,
        CLI,
        STDLIB_STATE,
        CLI,
        STDLIB_STATE,
        name,
        name,
    )


def run_rule(name):
    return """\
(rule
 (alias runtest)
 (target %s.actual)
 (deps
  run_case.sh
  %s.cljc
  %s.expected
  %s
  %s
  %s)
 (action
  (progn
   (with-stdout-to
    %%{target}
    (run
     sh
     %%{dep:run_case.sh}
     run
     %%{exe:%s}
     %%{dep:%s}
     %%{dep:%s}
     %%{dep:%s.cljc}))
   (diff %%{dep:%s.expected} %%{target}))))
""" % (
        name,
        name,
        name,
        CLI,
        STDLIB_STATE,
        STDLIB_ML,
        CLI,
        STDLIB_STATE,
        STDLIB_ML,
        name,
        name,
    )


def main():
    cases = {}
    for entry in os.listdir(GOLDEN):
        stem, dot, ext = entry.rpartition(".")
        if not dot:
            continue
        if ext == "cljc":
            cases.setdefault(stem, set()).add("cljc")
        elif ext == "run":
            cases.setdefault(stem, set()).add("run")
        elif ext == "expected":
            cases.setdefault(stem, set()).add("expected")
    out = ["; Generated by gen_dune_inc.py — do not edit; run dune promote.\n"]
    for stem in sorted(cases):
        kinds = cases[stem]
        if "cljc" not in kinds:
            sys.stderr.write(
                "gen_dune_inc.py: %s has no .cljc; skipping\n" % stem
            )
            continue
        if "expected" not in kinds:
            sys.stderr.write(
                "gen_dune_inc.py: %s.cljc has no .expected; "
                "run `dune build @runtest && dune promote` to create it\n" % stem
            )
        out.append(run_rule(stem) if "run" in kinds else compile_rule(stem))
        out.append("\n")
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
