#!/usr/bin/env python3
"""Generate src/error_docs.ml embedding docs/errors/*.md.

Also validates registry parity: every error code declared in
src/error_code.ml has a docs/errors/<CODE>.md file, and no markdown file
exists without a matching code.
"""
import os, re, sys, glob

ROOT = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()

codes = set(re.findall(r'"(LG\d{4})"', open(os.path.join(ROOT, "src/error_code.ml")).read()))
docs = sorted(glob.glob(os.path.join(ROOT, "docs/errors/LG*.md")))
doc_codes = {os.path.basename(p)[:6] for p in docs}

missing = codes - doc_codes
orphans = doc_codes - codes
if missing:
    sys.exit(f"error codes missing docs: {sorted(missing)}")
if orphans:
    sys.exit(f"orphan docs without an error code: {sorted(orphans)}")

entries = []
for path in docs:
    rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
    body = open(path).read()
    if "|}" in body:
        sys.exit(f"{rel}: body contains the |}} terminator")
    entries.append(f'    ("{rel}", {{|{body}|}})')

print("(* Generated by gen_error_docs.py from docs/errors/*.md; do not edit. *)")
print("let docs : (string * string) list =")
print("  [")
print(";\n".join(entries))
print("  ]")
